### ISSUE TITLE
write ending

### ISSUE THREAD

**Issue by jamen** [audiojs/web-audio-stream#10]
On audio-speaker 2.0 for browser, caught a bug with the write ending in web-audio-stream (at https://github.com/audiojs/audio-speaker/pull/44) as detailed in the PR

A few weeks back I tried using some of `ScriptProcessorNode`'s events ([documented on MDN](https://developer.mozilla.org/en-US/docs/Web/API/ScriptProcessorNode)) to solve this:

- [complete](https://developer.mozilla.org/en-US/docs/Web/Events/complete)
- [onend](https://developer.mozilla.org/en-US/docs/Web/Events/ended)
- [statechange](https://developer.mozilla.org/en-US/docs/Web/Events/statechange)
- ...
- [audioprocess](https://developer.mozilla.org/en-US/docs/Web/Events/audioprocess)

None of these besides `audioprocess` seemed to actually do anything under `ctx.destination`, which you had already seemed to be using.  So I'm curious how we should solve this.

Ideas? @dfcreative @connorhartley :smile:

**Comment by dy** [comment]
@jamen can you please show a test-case for that? Not really following what you mean. The basic premise is that `write(null)` should disconnect _ScriptProcessorNode_ and end streaming if there is any. Also I am not sure why is it addressed here, not in [web-audio-write](https://github.com/audiojs/web-audio-write), I believe we should not use _web-audio-stream_ in _audio-speaker_ at all.

**Comment by jamen** [comment]
@dfcreative My bad.  There is still `web-audio-stream/write` here on the master branch, and you splitting the package had jogged my memory.  Moving.

**Comment by dy** [comment]
@jamen is this issue still actual for web-audio-write? I can fix while at it
